spring:
  application:
    name: categorizer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/josemi
  datasource:
    username: postgres
    password: fenix000
    url: jdbc:postgresql://localhost:5432/categorizer
    
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - "*"
          
openapi:
  categorizer:
    base-path: /categorizer/v1
