spring:
  application:
    name: categorizer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/josemi
          
          
openapi:
  categorizer:
    base-path: /categorizer/v1
